on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['20.x']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install, build and test
      run: |
        npm install
        npm run build
   
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: dist/ # path/to/artifact
  deploy:
  # Add a dependency to the build job
  needs: build

  # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  permissions:
    pages: write      # to deploy to Pages
    id-token: write   # to verify the deployment originates from an appropriate source

  # Deploy to the github-pages environment
  environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}

  # Specify runner + deployment step
  runs-on: ubuntu-latest
  steps:
    - name: Deploy to GitHub Pages
      id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
        
